// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Issue49329Example.Migrations;

[DbContext(typeof(MyDbContext))]
[Migration("00000000000000_InitialState.cs")]
partial class InitialState
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("FriendlyName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Xml")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("DataProtectionKeys");
            });
#pragma warning restore 612, 618
    }
}